name: Build and Test

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    env:
      MAVEN_OPTS: "-Xmx1024m -XX:MaxMetaspaceSize=256m -Dorg.slf4j.simpleLogger.defaultLogLevel=error"
      CI: true
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
    
    - name: Cache Maven dependencies
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
    
    - name: Install ZSH
      run: |
        sudo apt-get update
        sudo apt-get install -y zsh
      shell: bash
        
    - name: Run tests
      run: |
        mvn clean test -q -B \
          -Dorg.slf4j.simpleLogger.defaultLogLevel=error \
          -Dorg.slf4j.simpleLogger.log.org.springframework=error \
          -Dorg.slf4j.simpleLogger.log.org.hibernate=error \
          -Dorg.slf4j.simpleLogger.log.com.rbatllet=error \
          -Dmaven.test.failure.ignore=false \
          -Dlogback.configurationFile=src/test/resources/logback-test.xml
      shell: zsh {0}
    
    - name: Build JAR with dependencies  
      run: |
        mvn clean package -q -B \
          -Dorg.slf4j.simpleLogger.defaultLogLevel=error \
          -Dorg.slf4j.simpleLogger.log.org.springframework=error \
          -Dorg.slf4j.simpleLogger.log.org.hibernate=error \
          -DskipTests=true \
          -Dmaven.javadoc.skip=true
      shell: zsh {0}
    
    - name: Upload JAR artifacts
      uses: actions/upload-artifact@v4
      if: success()
      with:
        name: private-blockchain-jars
        path: target/*.jar
        retention-days: 30
        compression-level: 6
    
    - name: Upload test results  
      uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: test-results-${{ github.run_number }}
        path: target/surefire-reports/
        retention-days: 7