name: Build and Test

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
    
    - name: Cache Maven dependencies
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
    
    - name: Install ZSH
      run: |
        sudo apt-get update
        sudo apt-get install -y zsh
      shell: bash
        
    - name: Run tests
      run: mvn clean test
      shell: zsh {0}
    
    - name: Build JAR with dependencies
      run: mvn clean package
      shell: zsh {0}
    
    - name: Upload JAR artifacts
      uses: actions/upload-artifact@v4
      with:
        name: private-blockchain-jars
        path: |
          target/*.jar
        retention-days: 30
    
    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results
        path: target/surefire-reports/
        retention-days: 30